### ISSUE TITLE
Move the cache scripts to its own repo and package

### ISSUE THREAD

**Issue by daviddavo** [Grasia/dao-analyzer#150]
- If something has its own version number, it should be a different package / repo. 
- Furthermore, some people want to just use our dataset and not the DAO-Analyzer tool.
- We want to add new platforms to the data that might not be used by dao-analyzer. The development of dao-analyzer and its cache scripts might not be coordinated. Therefore, we could pin an exact version of the cache-scripts and avoid interfacing problems.

## Tasks
- [x] Create repository with src ([grasia/dao-scripts](https://github.com/grasia/dao-analyzer))
- [x] CI to publish package
- [x] Make the dao-scripts package a dep of dao-analyzer and delete the source code from this repo
